name: Build Mod

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android64
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Geode Mod
      uses: geode-sdk/build-geode-mod@main
      with:
        target: 'Android64'

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dm.ai-deco-assistant
        path: build/*.geode
